version: '3.9'
services:
  ecomm:
    build: .
    image: ecomm:4.0
    ports:
      - 3000:3000
    depends_on:
      - mongo-ecomm
    links:
      - mongo-ecomm
    environment:
      MONGO_HOST: mongo-ecomm

  mongo-ecomm:
    image: mongo
    container_name: mongo-ecomm
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - db-mongo-ecomm:/data/db
      - type: bind
        source: ./mongo
        target: /mongo-scripts
    restart: always
    ports:
      - 27017:27017

volumes:
  db-mongo-ecomm:
