openapi: 3.0.3
info:
  title: Swagger ECOMM - OpenAPI 3.0
  description: API usada para curso da Alura Level Up - Next Dev
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://localhost:3000
tags:
  - name: category
    description: Categorias de produtos 
paths:
  /api/categories:
    get:
      tags:
        - category
      summary: Get all categories
      description: Retorna todas as categorias com nome e status
      operationId: findCategories
      responses: 
        '200':
          description: SUCESSO!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/categories"
        '404':
          description: Nenhuma categoria encontrada
          content:
            application/json:
              example: "Not Found"
  /api/categories/{id}:
    get:
      tags:
        - category
      summary: Get one category
      description: Retorna uma categoria especifica
      operationId: findCategoryById
      parameters:
        - name: id
          in: path
          description: id da categoria
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: SUCESSO!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/categories"
        '404':
          description: Nenhuma categoria encontrada
          content:
            application/json:
              example: "Not Found"        
  /api/admin/categories:
    post:
      tags:
        - category
      summary: Create one category
      description: Cria uma categoria com nome e status
      operationId: createCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createCategory"
      responses:
        '201':
          description: Categoria criada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
        '404':
          description: Erro ao criar categoria
          content:
            application/json:
              example: "Not found"
  /api/admin/categories/update/{id}:
    put:
      tags:
        - category
      summary: Update a category
      description: Atualiza uma categoria
      operationId: updateCategory
      parameters:
        - name: id
          in: path
          description: id da categoria
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createCategory"
      responses:
        '200':
          description: Categoria atualizada!!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
        '404':
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found"
        '400':
          description: Requisição mal formatada
          content:
            application/json:
              example: "Bad Request"
  /api/admin/categories/remove/{id}:
    delete:
      tags:
        - category
      summary: Remove a category
      description: Remove uma categoria
      operationId: deleteCategory
      parameters: 
        - name: id
          in: path
          description: id da categoria
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200': 
          description: Categoria removida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
        '404':
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found"
        '400':
          description: Requisição mal formatada
          content:
            application/json:
              example: "Bad Request"
  /api/admin/categories/active/{id}:
    put:
      tags:
        - category
      summary: Active a category
      description: Ativa uma categoria já existente
      operationId: activeCategory
      parameters:
        - name: id
          in: path
          description: id da categoria
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200': 
          description: Categoria ativada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
        '404':
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found"
        '400':
          description: Requisição mal formatada
          content:
            application/json:
              example: "Bad Request"      
components:
  schemas:
    category:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
    categories:
      type: array
      items:
        $ref: "#/components/schemas/category"
    createCategory:
      type: object
      properties:
        nome: 
          type: string
        status: 
          type: string
        